Items:
  ShowcaseItem:
    ItemMaterialType: PAPER
    ItemAmount: '1'
    #CustomModelData is used for textures with ItemMaterial and texturepack
    CustomModelData: '0'
    #ItemName used in system and command such as /create, keep it as one sentience
    ItemName: ShowcaseItem
    Unbreakable: true
    DisplayName: '<grey>Showcase item name'
    Lore:
      LoreText:
        - ''
        - '<grey>Buty dające styl'
        - '<grey>Oraz prędkość wiatru'
        - ''
    Enchants:
      Enchant: luck_of_the_sea:1,unbreaking:3
  Default1:
    ItemMaterialType: STONE
    ItemAmount: '1'
    CustomModelData: '0'
    ItemName: DefaultItem
    Unbreakable: true
    DisplayName: '<grey>Default Item'
    Lore:
      LoreText:
        - ''
        - '<grey>Buty dające styl'
        - '<grey>Oraz prędkość wiatru'
        - ''
    Enchants:
      Enchant: luck_of_the_sea:1