name: SimpleRPG
version: 0.7.3
main: mc.theKOXpoland.SimpleRPG.MainFile
author: theKOXpoland
api-version: "1.20"
depend: [CommandAPI, Citizens, Sentinel]

commands:
  spiraltest:
    aliases: [st]