Weapons:
  ShowcaseItem:
    ItemMaterialType: IRON_SWORD
    ItemAmount: '1'
    #CustomModelData is used for textures with ItemMaterial and texturepack
    CustomModelData: '0'
    #Name used in system and command such as /create, keep it as one sentience
    ItemName: ShowcaseWeaponItem
    #CustomType options: Sword
    CustomType: Sword
    #Basic damage is 1, every number provided lower is ADDED to 1. Example: Damage: 1 will be 2 (1+1)
    Damage: '0.5'
    Unbreakable: true
    DisplayName: '<grey>Showcase item name'
    #AttackSpeed options: UltraSlow, VerySlow, Slow, Normal, Fast, VeryFast, UltraFast, Basic (Basic weapon speed)
    AttackSpeed: Basic
    Attacks:
      #PPM Attack
      FirstAttack: test1
      #Drop (Q) Attack
      SecondAttack: test2
    Lore:
      LoreText:
        - ''
        - '<grey>Obrażenia: %damage%'
        - '<grey>Prędkość: %attackSpeed%'
        - ''
        - '<grey>Umiejętność <gold>PPM: %first_attack%'
        - '<grey>Umiejętność <gold>Q: %second_attack%'
        - ''
    Enchants:
      #Enchant:level, enchant name provided from /enchant command
      Enchant: luck_of_the_sea:1,unbreaking:3
  Default2:
    ItemMaterialType: STONE_SWORD
    ItemAmount: '1'
    CustomModelData: '0'
    ItemName: PodstawowaNazwa1
    CustomType: Sword
    Damage: '0'
    Unbreakable: true
    DisplayName: '<grey>Podstawowa nazwa do wyświetlenia1'
    AttackSpeed: VerySlow
    Attacks:
      FirstAttack: test1
      SecondAttack: test2
    Lore:
      LoreText:
        - ''
        - '<grey>Obrażenia: %damage%'
        - '<grey>Prędkość: %attackSpeed%'
        - ''
        - '<grey>Umiejętność <gold>PPM: %first_attack%'
        - '<grey>Umiejętność <gold>Q: %second_attack%'
        - ''
    Enchants:
      Enchant: luck_of_the_sea:1
  Default3:
    ItemMaterialType: IRON_SWORD
    ItemAmount: '1'
    CustomModelData: '0'
    ItemName: PodstawowaNazwa2
    CustomType: Sword
    Damage: '-1'
    Unbreakable: true
    DisplayName: '<grey>Podstawowa nazwa do wyświetlenia2'
    AttackSpeed: Normal
    Attacks:
      FirstAttack: test1
      SecondAttack: test2
    Lore:
      LoreText:
        - ''
        - '<grey>Obrażenia: %damage%'
        - '<grey>Prędkość: %attackSpeed%'
        - ''
        - '<grey>Umiejętność <gold>PPM: %first_attack%'
        - '<grey>Umiejętność <gold>Q: %second_attack%'
        - ''
    Enchants:
      Enchant: luck_of_the_sea:1
  Default4:
    ItemMaterialType: DIAMOND_SWORD
    ItemAmount: '1'
    CustomModelData: '0'
    ItemName: PodstawowaNazwa3
    CustomType: Sword
    Damage: '1'
    Unbreakable: true
    DisplayName: '<grey>Podstawowa nazwa do wyświetlenia3'
    AttackSpeed: VeryFast
    Attacks:
      FirstAttack: test1
      SecondAttack: test2
    Lore:
      LoreText:
        - ''
        - '<grey>Obrażenia: %damage%'
        - '<grey>Prędkość: %attackSpeed%'
        - ''
        - '<grey>Umiejętność <gold>PPM: %first_attack%'
        - '<grey>Umiejętność <gold>Q: %second_attack%'
        - ''
    Enchants:
      Enchant: luck_of_the_sea:1